In [4]:
import pandas as pd

In [23]:
data = pd.read_csv('owid-covid-data.csv')
data

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-01-03,0,0.0,NaN,0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-01-04,0,0.0,NaN,0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-01-05,0,0.0,NaN,0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-01-06,0,0.0,NaN,0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-01-07,0,0.0,NaN,0,0.0,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
353743,ZWE,Africa,Zimbabwe,2023-10-29,265821,0.0,0.0,5720,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
353744,ZWE,Africa,Zimbabwe,2023-10-30,265821,0.0,0.0,5720,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
353745,ZWE,Africa,Zimbabwe,2023-10-31,265821,0.0,0.0,5720,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
353746,ZWE,Africa,Zimbabwe,2023-11-01,265821,0.0,0.0,5720,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN
353747,ZWE,Africa,Zimbabwe,2023-11-02,265821,0.0,0.0,5720,0.0,0.0,...,30.7,36.791,1.7,61.49,0.571,16320539,NaN,NaN,NaN,NaN

In [24]:
data['total_cases']

0              0
1              0
2              0
3              0
4              0
           ...
353743    265821
353744    265821
353745    265821
353746    265821
353747    265821
Name: total_cases, Length: 353748, dtype: int64

In [25]:
list_

NameError: name 'list_' is not defined

In [26]:
WEU = [
    'Andorra',
    'Austria',
    'Belgium',
    'England',
    'France',
    'Guernsey',
    'Iceland',
    'Ireland',
    'Isle of Man',
    'Italy',
    'Jersey',
    'Luxembourg',
    'Netherlands',
    'Poland',
    'Portugal',
    'Scotland',
    'Spain',
    'Sweden',
    'United Kingdom',
    'Wales']

In [42]:
pd.DataFrame(columns=["date", "loc", "total_cases",'total_deaths','people_vaccinated'])

Empty DataFrame
Columns: [date, loc, total_cases, total_deaths, people_vaccinated]
Index: []

In [27]:
def column_sum(key,column_name,group):
    group[column_name].sum()

In [41]:
MAS = ['Afghanistan','Bahrain','Kuwait','Saudi Arabia',]
KOR = ['South Korea']
JPN = ['Japan']
CHN = ['China']
HKO = ['Hong Kong']
ASIA = ['Armenia','Azerbaijan','Bangladesh','Bhutan','Brunei','Cambodia','Georgia','India','Indonesia','Iran','Iraq','Israel','Jordan',
      'Kazakhstan','Kyrgyzstan','Laos','Lebanon','Macao','Malaysia','Maldives','Myanmar','Nepal','Northern Cyprus','Oman','Pakistan',
      'Palestine','Philippines','Qatar','Singapore','Sri Lanka','Syria','Taiwan','Tajikistan','United Arab Emirates','Uzbekistan','Vietnam','Yemen']
# 중동,한국,일본,중국,홍콩을 제외한 나라는 아시아로 통합하여 분류하였고 
#중국에 속하지만 마카오는 아시아로 분류함
DATA_LIST=['USA','NAM','KOR','SAM','JPN','CHN','RSI','EEU','WEU','MAS','AUS','AFR','SAF','HKO','ASIA']
data_dict={i:pd.DataFrame(columns=["date", "loc", "total_cases",'total_deaths','people_vaccinated']) for i in DATA_LIST}
for date , date_group in data.groupby('date'):
    if date[-2:]=='01':
        DATA_LIST2=['USA','NAM','KOR','SAM','JPN','CHN','RSI','EEU','WEU','MAS','AUS','AFR','SAF','HKO','ASIA']
        data_dict2={i:pd.DataFrame({}) for i in DATA_LIST}
        for continent, continent_group in date_group.groupby('continent'):
            for location,location_group in continent_group.groupby('location'):
               
                if continent=='Africa':
                    if location=='South Africa':
                        data_dict2['SAF']=pd.concat([data_dict2.get('SAF',pd.DataFrame({})),location_group]) 
                    else:
                        data_dict2['AFR']=pd.concat([data_dict2.get('AFR',pd.DataFrame({})),location_group])
                elif continent=='Asia':
                    if location=='South Korea':
                        data_dict2['KOR']=pd.concat([data_dict2.get('KOR',pd.DataFrame({})),location_group])

                    elif location=='Japan':
                        data_dict2['JPN']=pd.concat([data_dict2.get('JPN',pd.DataFrame({})),location_group])

                    elif location in MAS:
                        data_dict2['MAS']=pd.concat([data_dict2.get('MAS',pd.DataFrame({})),location_group])

                    elif location=='China':
                        data_dict2['CHN']=pd.concat([data_dict2.get('CHN',pd.DataFrame({})),location_group])

                    elif location=='Hong Kong':
                        data_dict2['HKO']=pd.concat([data_dict2.get('HKO',pd.DataFrame({})),location_group])

                    else:
                        data_dict2['ASIA']=pd.concat([data_dict2.get('ASIA',pd.DataFrame({})),location_group])

                elif continent=='Europe':
                    if location=='Russia':
                        data_dict2['RSI']=pd.concat([data_dict2.get('RSI',pd.DataFrame({})),location_group])
                    elif location in WEU:
                        data_dict2['WEU']=pd.concat([data_dict2.get('WEU',pd.DataFrame({})),location_group])
                    else:
                        data_dict2['EEU']=pd.concat([data_dict2.get('EEU',pd.DataFrame({})),location_group])
                    pass
                elif continent=='North America':
                    if location=='United States':
                        data_dict2['USA']=pd.concat([data_dict2.get('USA',pd.DataFrame({})),location_group])
                    else:
                        data_dict2['NAM']=pd.concat([data_dict2.get('NAM',pd.DataFrame({})),location_group])
                elif continent=='Oceania':
                    data_dict2['AUS']=pd.concat([data_dict2.get('AUS',pd.DataFrame({})),location_group])

                elif continent=='South America':
                    data_dict2['SAM']=pd.concat([data_dict2.get('SAM',pd.DataFrame({})),location_group])
        for loc,dp in data_dict2.items():
            data_dict[loc].append({'date':date,'loc':loc,'total_cases':dp['total_cases'].sum(),'total_deaths':dp['total_deaths'].sum(),'people_vaccinated':dp['people_vaccinated'].sum()})
#data_dict[loc]가 dataframe 어팬드안에 있는 행을 추가하면 됨
data_dict['KOR']

KeyError: 'total_cases'

In [11]:
for date,date_grouped in data.groupby('date'):
    print(date[-2:])

01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
01
02
03
04
05
06

In [119]:
for key, value in data_dict.items():
    for date,date_grouped in value.groupby('date'):
        if date[-2:]=='01'

In [119]:
for key, value in data_dict.items():
    filename = f'country/{key}.csv'
    value.to_csv(filename, index=False)

In [99]:
grouped = data.groupby('continent')
am={}
cnt=0
list_=
for country, group in grouped:
    filename = f'country/{country}.csv'
    group.to_csv(filename, index=False)
    list_.append(country)
    cnt+=1
print(cnt)

       iso_code continent      location        date  total_cases  new_cases  \
292387      ZAF    Africa  South Africa  2020-01-03          NaN        0.0
292388      ZAF    Africa  South Africa  2020-01-04          NaN        0.0
292389      ZAF    Africa  South Africa  2020-01-05          NaN        0.0
292390      ZAF    Africa  South Africa  2020-01-06          NaN        0.0
292391      ZAF    Africa  South Africa  2020-01-07          NaN        0.0
...         ...       ...           ...         ...          ...        ...
293782      ZAF    Africa  South Africa  2023-10-29    4072533.0        0.0
293783      ZAF    Africa  South Africa  2023-10-30    4072533.0        0.0
293784      ZAF    Africa  South Africa  2023-10-31    4072533.0        0.0
293785      ZAF    Africa  South Africa  2023-11-01    4072533.0        0.0
293786      ZAF    Africa  South Africa  2023-11-02    4072533.0        0.0

        new_cases_smoothed  total_deaths  new_deaths  new_deaths_smoothed  \
292387                 NaN           NaN         0.0                  NaN
292388                 NaN           NaN         0.0                  NaN
292389                 NaN           NaN         0.0                  NaN
292390                 NaN           NaN         0.0                  NaN
292391                 NaN           NaN         0.0                  NaN
...                    ...           ...         ...                  ...
293782                 0.0      102595.0         0.0                  0.0
293783                 0.0      102595.0         0.0                  0.0
293784                 0.0      102595.0         0.0                  0.0
293785                 0.0      102595.0         0.0                  0.0
293786                 0.0      102595.0         0.0                  0.0

        ...  male_smokers  handwashing_facilities  hospital_beds_per_thousand  \
292387  ...          33.2                  43.993                        2.32
292388  ...          33.2                  43.993                        2.32
292389  ...          33.2                  43.993                        2.32
292390  ...          33.2                  43.993                        2.32
292391  ...          33.2                  43.993                        2.32
...     ...           ...                     ...                         ...
293782  ...          33.2                  43.993                        2.32
293783  ...          33.2                  43.993                        2.32
293784  ...          33.2                  43.993                        2.32
293785  ...          33.2                  43.993                        2.32
293786  ...          33.2                  43.993                        2.32

        life_expectancy  human_development_index  population  \
292387            64.13                    0.709  59893884.0
292388            64.13                    0.709  59893884.0
292389            64.13                    0.709  59893884.0
292390            64.13                    0.709  59893884.0
292391            64.13                    0.709  59893884.0
...                 ...                      ...         ...
293782            64.13                    0.709  59893884.0
293783            64.13                    0.709  59893884.0
293784            64.13                    0.709  59893884.0
293785            64.13                    0.709  59893884.0
293786            64.13                    0.709  59893884.0

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
292387                                   NaN                          NaN
292388                                   NaN                          NaN
292389                                 245.1                         2.41
292390                                   NaN                          NaN
292391                                   NaN                          NaN
...                                      ...                          ...
293782                                   NaN                          NaN
293783                                   NaN                          NaN
293784                                   NaN                          NaN
293785                                   NaN                          NaN
293786                                   NaN                          NaN

        excess_mortality  excess_mortality_cumulative_per_million
292387               NaN                                      NaN
292388               NaN                                      NaN
292389              2.41                                 4.168231
292390               NaN                                      NaN
292391               NaN                                      NaN
...                  ...                                      ...
293782               NaN                                      NaN
293783               NaN                                      NaN
293784               NaN                                      NaN
293785               NaN                                      NaN
293786               NaN                                      NaN

[1400 rows x 67 columns]

In [65]:
america=['Afghanistan',
 'Africa',
 'Albania',
 'Algeria',
 'American Samoa']

In [69]:
list_

['Afghanistan',
 'Africa',
 'Albania',
 'Algeria',
 'American Samoa',
 'Andorra',
 'Angola',
 'Anguilla',
 'Antigua and Barbuda',
 'Argentina',
 'Armenia',
 'Aruba',
 'Asia',
 'Australia',
 'Austria',
 'Azerbaijan',
 'Bahamas',
 'Bahrain',
 'Bangladesh',
 'Barbados',
 'Belarus',
 'Belgium',
 'Belize',
 'Benin',
 'Bermuda',
 'Bhutan',
 'Bolivia',
 'Bonaire Sint Eustatius and Saba',
 'Bosnia and Herzegovina',
 'Botswana',
 'Brazil',
 'British Virgin Islands',
 'Brunei',
 'Bulgaria',
 'Burkina Faso',
 'Burundi',
 'Cambodia',
 'Cameroon',
 'Canada',
 'Cape Verde',
 'Cayman Islands',
 'Central African Republic',
 'Chad',
 'Chile',
 'China',
 'Colombia',
 'Comoros',
 'Congo',
 'Cook Islands',
 'Costa Rica',
 "Cote d'Ivoire",
 'Croatia',
 'Cuba',
 'Curacao',
 'Cyprus',
 'Czechia',
 'Democratic Republic of Congo',
 'Denmark',
 'Djibouti',
 'Dominica',
 'Dominican Republic',
 'Ecuador',
 'Egypt',
 'El Salvador',
 'England',
 'Equatorial Guinea',
 'Eritrea',
 'Estonia',
 'Eswatini',
 'Ethiopia',
 'Europe',
 'European Union',
 'Faeroe Islands',
 'Falkland Islands',
 'Fiji',
 'Finland',
 'France',
 'French Guiana',
 'French Polynesia',
 'Gabon',
 'Gambia',
 'Georgia',
 'Germany',
 'Ghana',
 'Gibraltar',
 'Greece',
 'Greenland',
 'Grenada',
 'Guadeloupe',
 'Guam',
 'Guatemala',
 'Guernsey',
 'Guinea',
 'Guinea-Bissau',
 'Guyana',
 'Haiti',
 'High income',
 'Honduras',
 'Hong Kong',
 'Hungary',
 'Iceland',
 'India',
 'Indonesia',
 'Iran',
 'Iraq',
 'Ireland',
 'Isle of Man',
 'Israel',
 'Italy',
 'Jamaica',
 'Japan',
 'Jersey',
 'Jordan',
 'Kazakhstan',
 'Kenya',
 'Kiribati',
 'Kosovo',
 'Kuwait',
 'Kyrgyzstan',
 'Laos',
 'Latvia',
 'Lebanon',
 'Lesotho',
 'Liberia',
 'Libya',
 'Liechtenstein',
 'Lithuania',
 'Low income',
 'Lower middle income',
 'Luxembourg',
 'Macao',
 'Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia (country)',
 'Moldova',
 'Monaco',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North America',
 'North Korea',
 'North Macedonia',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Oceania',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (French part)',
 'Saint Pierre and Miquelon',
 'Saint Vincent and the Grenadines',
 'Samoa',
 'San Marino',
 'Sao Tome and Principe',
 'Saudi Arabia',
 'Scotland',
 'Senegal',
 'Serbia',
 'Seychelles',
 'Sierra Leone',
 'Singapore',
 'Sint Maarten (Dutch part)',
 'Slovakia',
 'Slovenia',
 'Solomon Islands',
 'Somalia',
 'South Africa',
 'South America',
 'South Korea',
 'South Sudan',
 'Spain',
 'Sri Lanka',
 'Sudan',
 'Suriname',
 'Sweden',
 'Switzerland',
 'Syria',
 'Taiwan',
 'Tajikistan',
 'Tanzania',
 'Thailand',
 'Timor',
 'Togo',
 'Tokelau',
 'Tonga',
 'Trinidad and Tobago',
 'Tunisia',
 'Turkey',
 'Turkmenistan',
 'Turks and Caicos Islands',
 'Tuvalu',
 'Uganda',
 'Ukraine',
 'United Arab Emirates',
 'United Kingdom',
 'United States',
 'United States Virgin Islands',
 'Upper middle income',
 'Uruguay',
 'Uzbekistan',
 'Vanuatu',
 'Vatican',
 'Venezuela',
 'Vietnam',
 'Wales',
 'Wallis and Futuna',
 'Western Sahara',
 'World',
 'Yemen',
 'Zambia',
 'Zimbabwe']

In [79]:
countries = [
    'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 'Antigua and Barbuda',
    'Argentina', 'Armenia', 'Aruba', 'Asia', 'Australia', 'Austria', 'Azerbaijan', 'Bahamas',
    'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 'Belize', 'Benin', 'Bermuda',
    'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba', 'Bosnia and Herzegovina', 'Botswana',
    'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso', 'Burundi', 'Cambodia',
    'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
    'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 'Costa Rica', "Cote d'Ivoire", 'Croatia',
    'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Democratic Republic of Congo', 'Denmark', 'Djibouti',
    'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador', 'England', 'Equatorial Guinea',
    'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 'European Union', 'Faeroe Islands',
    'Falkland Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 'French Polynesia', 'Gabon',
    'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 'Grenada',
    'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti',
    'High income', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran',
    'Iraq', 'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan',
    'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
    'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Lithuania', 'Low income', 'Lower middle income',
    'Luxembourg', 'Macao', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
    'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Mayotte', 'Mexico', 'Micronesia (country)',
    'Moldova', 'Monaco', 'Mon', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique', 'Myanmar',
    'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 'New Zealand', 'Nicaragua', 'Niger',
    'Nigeria', 'Niue', 'North America', 'North Korea', 'North Macedonia', 'Northern Cyprus',
    'Northern Ireland', 'Northern Mariana Islands', 'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau',
    'Palestine', 'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland',
    'Portugal', 'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Barthelemy',
    'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (French part)',
    'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
    'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Seychelles',
    'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands',
    'Somalia', 'South Africa', 'South America', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka',
    'Sudan', 'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
    'Thailand', 'Timor', 'Togo', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
    'Turkmenistan', 'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates',
    'United Kingdom', 'United States', 'United States Virgin Islands', 'Upper middle income', 'Uruguay',
    'Uzbekistan', 'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam', 'Wales', 'Wallis and Futuna',
    'Western Sahara', 'World', 'Yemen', 'Zambia', 'Zimbabwe'
]
len(countries)

254

In [88]:
countries[129:193]

['Madagascar',
 'Malawi',
 'Malaysia',
 'Maldives',
 'Mali',
 'Malta',
 'Marshall Islands',
 'Martinique',
 'Mauritania',
 'Mauritius',
 'Mayotte',
 'Mexico',
 'Micronesia (country)',
 'Moldova',
 'Monaco',
 'Mon',
 'Mongolia',
 'Montenegro',
 'Montserrat',
 'Morocco',
 'Mozambique',
 'Myanmar',
 'Namibia',
 'Nauru',
 'Nepal',
 'Netherlands',
 'New Caledonia',
 'New Zealand',
 'Nicaragua',
 'Niger',
 'Nigeria',
 'Niue',
 'North America',
 'North Korea',
 'North Macedonia',
 'Northern Cyprus',
 'Northern Ireland',
 'Northern Mariana Islands',
 'Norway',
 'Oceania',
 'Oman',
 'Pakistan',
 'Palau',
 'Palestine',
 'Panama',
 'Papua New Guinea',
 'Paraguay',
 'Peru',
 'Philippines',
 'Pitcairn',
 'Poland',
 'Portugal',
 'Puerto Rico',
 'Qatar',
 'Reunion',
 'Romania',
 'Russia',
 'Rwanda',
 'Saint Barthelemy',
 'Saint Helena',
 'Saint Kitts and Nevis',
 'Saint Lucia',
 'Saint Martin (French part)',
 'Saint Pierre and Miquelon']